
# SERVER CONFIGURATION
server.port=${PORT:8080}
spring.application.name=food-delivery

# MYSQL DATABASE CONFIGURATION
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/foodapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Deepa@567}

# JPA & HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

